apiVersion: triliovault.trilio.io/v1
kind: Backup
metadata:
  name: postgres-full-backup
spec:
  type: Full
  scheduleType: Periodic
  backupPlan:
    name: postgres-backupplan
    namespace: postgres
